config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'pets', to: 'pets#index'
  get 'pets/new', to: 'pets#new'
  post 'pets', to: 'pets#create'
  get 'pets/:id', to: 'pets#show', as: 'pet'
  get 'pets/:id/edit', to: 'pets#edit', as: 'edit_pet'
  patch 'pets/:id', to: 'pets#update'
  delete 'pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w[dog cat rabbit snake turtle].freeze
  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    return unless found_on # evita que o método quebre se o found_on for nil

    (Date.current - found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]

  def index
    @pets = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit; end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path, status: :see_other
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lww1425LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="container m-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <div class="d-flex">
    <%= f.input :species, collection: Pet::SPECIES %>
    <%= f.input :found_on, html5: true %>
  </div>
  <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit pet</h1>
<%= render 'form', pet: @pet %>
<hr>
<%= link_to 'Back', pet_path(@pet) %>

app/views/pets/index.html.erb
<h1>All pets</h1>
<%= link_to 'Add pet', pets_new_path, class: 'btn btn-primary mb-4' %>
<div class="row">
  <% @pets.each do |pet| %>
    <div class="col-12 col-md-4 col-lg-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to pet.name, pet_path(pet) %></h5>
          <p class="card-text"><% if pet.found_on  %>Found <%= pet.found_days_ago %> <%= 'day'.pluralize(pet.found_days_ago) %> ago <% end %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
<ul>
</ul>

app/views/pets/new.html.erb
<h1>Add a new pet</h1>
<%= render 'form', pet: @pet %>
<hr>
<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<div class="card">
  <h1 class="card-title">
    <%= @pet.name %></h1>
  </h1>
  <div class="card-body">
    <p>Found <%= @pet.found_days_ago %> days ago</p>
    <p>Address: <%= @pet.address %></p>
    <p>Species: <%= @pet.species %></p>
    <%= link_to 'Edit', edit_pet_path(@pet), class: 'btn btn-primary' %>
    <%= link_to 'Delete', pet_path(@pet), data: {turbo_method: 'delete', turbo_confirm: 'Are you sure?'}, class: 'btn btn-danger' %>

  </div>
</div>
<hr>
<%= link_to 'Back', pets_path %>